//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input Manager/inputManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputManager : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""inputManager"",
    ""maps"": [
        {
            ""name"": ""Giocatore"",
            ""id"": ""b21a0be6-3c7c-4fde-92ba-d951174c29dc"",
            ""actions"": [
                {
                    ""name"": ""Movimento"",
                    ""type"": ""Value"",
                    ""id"": ""e1bc9d7d-8d45-4e0b-ba35-71b1c685151a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotazioneVista"",
                    ""type"": ""Value"",
                    ""id"": ""48b4a186-eefa-4850-af5b-6ce767905507"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Salto"",
                    ""type"": ""Button"",
                    ""id"": ""da53dde3-9ec9-45a7-86c1-66fca2ac177d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MeleeAtk"",
                    ""type"": ""Button"",
                    ""id"": ""82dc36c7-d7da-484a-a419-acdaa5f40eac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lingua"",
                    ""type"": ""Button"",
                    ""id"": ""f26f3809-c089-4931-ab45-7752eea8acba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScattoAcqua"",
                    ""type"": ""Button"",
                    ""id"": ""8aac8c6f-0920-4216-a798-fef701e96e0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interazione"",
                    ""type"": ""Button"",
                    ""id"": ""12316aeb-1073-4f32-a3d1-a1905924c474"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Tastiera [WASD]"",
                    ""id"": ""4dcc89e8-1e17-40d5-8b8b-021e323ed295"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ba46b25-ed3e-4578-b79b-b26a8e0c028b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""08a0f9be-3fe9-4422-8e0f-41f765a603b6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7670eb44-0675-4e6d-8475-4ddb554a2825"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9e5bc89b-3f9f-4042-8ac7-7a2708d248a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Tastiera [Frecce]"",
                    ""id"": ""5654333b-d7c2-47e8-bf0c-45ac3eb8bc30"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7cd6ec10-bd93-4550-a824-3f40d0009f98"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8efaed0b-d4bc-4642-92d2-34c7697cb817"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""09010cbd-52db-480f-8b43-0fa3e3f2c8db"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""be7c2f6a-8e27-468e-9a9b-4a576ab5eecc"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""36df8638-f75d-4386-8ec0-4d18303deeca"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""143f4fd8-43fb-455c-a4d6-15db997be33d"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6e10cfd5-5ccd-4098-a139-dc64e83b4d34"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9caf6f37-b258-40e4-ac57-20f8d95bc0ad"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6a953006-4a1c-46c0-b16a-b77fcdf57a04"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d37ec524-57ce-4209-b5ea-58f88a4f0bad"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotazioneVista"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e728320c-8936-4d6a-b7d2-5e40939877a9"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotazioneVista"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5e522b8-617c-4a43-9c99-2173b5402f1b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Salto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cb892f1-3821-4928-9bbc-336f321e4f88"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Salto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a162d99-8993-427c-8779-ff2177f33f07"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lingua"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c546326-f96f-4fc6-b880-52c80e41e9a3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lingua"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c441abc-3fd1-40f6-bf68-67da88cc9289"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MeleeAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f1c5447-e86a-42a7-b266-f283ef4f9b48"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MeleeAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19de8f13-93ce-459e-93d9-89d20aa93b64"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScattoAcqua"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb51c0f1-eae5-4cf5-b9ec-fb872793de08"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScattoAcqua"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""923e3fff-6b67-4339-95d6-99b3f3bb7d5f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interazione"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1684bd7-7d58-4aac-8eb2-0ca114ced9c0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interazione"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Generali"",
            ""id"": ""37d1c5cc-688c-4b22-9f63-71206622120b"",
            ""actions"": [
                {
                    ""name"": ""Pausa"",
                    ""type"": ""Button"",
                    ""id"": ""71dc6642-f5ed-4631-aaab-3d6e7ecf47ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9343ebad-568d-4dda-a089-0300db0535d9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77430a8b-a29a-43a7-aa96-7654c8c5a5f4"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cf72df0-cec6-42b4-abfe-94f5d1d29cd4"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Giocatore
        m_Giocatore = asset.FindActionMap("Giocatore", throwIfNotFound: true);
        m_Giocatore_Movimento = m_Giocatore.FindAction("Movimento", throwIfNotFound: true);
        m_Giocatore_RotazioneVista = m_Giocatore.FindAction("RotazioneVista", throwIfNotFound: true);
        m_Giocatore_Salto = m_Giocatore.FindAction("Salto", throwIfNotFound: true);
        m_Giocatore_MeleeAtk = m_Giocatore.FindAction("MeleeAtk", throwIfNotFound: true);
        m_Giocatore_Lingua = m_Giocatore.FindAction("Lingua", throwIfNotFound: true);
        m_Giocatore_ScattoAcqua = m_Giocatore.FindAction("ScattoAcqua", throwIfNotFound: true);
        m_Giocatore_Interazione = m_Giocatore.FindAction("Interazione", throwIfNotFound: true);
        // Generali
        m_Generali = asset.FindActionMap("Generali", throwIfNotFound: true);
        m_Generali_Pausa = m_Generali.FindAction("Pausa", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Giocatore
    private readonly InputActionMap m_Giocatore;
    private IGiocatoreActions m_GiocatoreActionsCallbackInterface;
    private readonly InputAction m_Giocatore_Movimento;
    private readonly InputAction m_Giocatore_RotazioneVista;
    private readonly InputAction m_Giocatore_Salto;
    private readonly InputAction m_Giocatore_MeleeAtk;
    private readonly InputAction m_Giocatore_Lingua;
    private readonly InputAction m_Giocatore_ScattoAcqua;
    private readonly InputAction m_Giocatore_Interazione;
    public struct GiocatoreActions
    {
        private @InputManager m_Wrapper;
        public GiocatoreActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimento => m_Wrapper.m_Giocatore_Movimento;
        public InputAction @RotazioneVista => m_Wrapper.m_Giocatore_RotazioneVista;
        public InputAction @Salto => m_Wrapper.m_Giocatore_Salto;
        public InputAction @MeleeAtk => m_Wrapper.m_Giocatore_MeleeAtk;
        public InputAction @Lingua => m_Wrapper.m_Giocatore_Lingua;
        public InputAction @ScattoAcqua => m_Wrapper.m_Giocatore_ScattoAcqua;
        public InputAction @Interazione => m_Wrapper.m_Giocatore_Interazione;
        public InputActionMap Get() { return m_Wrapper.m_Giocatore; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GiocatoreActions set) { return set.Get(); }
        public void SetCallbacks(IGiocatoreActions instance)
        {
            if (m_Wrapper.m_GiocatoreActionsCallbackInterface != null)
            {
                @Movimento.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnMovimento;
                @Movimento.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnMovimento;
                @Movimento.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnMovimento;
                @RotazioneVista.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnRotazioneVista;
                @RotazioneVista.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnRotazioneVista;
                @RotazioneVista.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnRotazioneVista;
                @Salto.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnSalto;
                @Salto.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnSalto;
                @Salto.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnSalto;
                @MeleeAtk.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnMeleeAtk;
                @MeleeAtk.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnMeleeAtk;
                @MeleeAtk.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnMeleeAtk;
                @Lingua.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnLingua;
                @Lingua.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnLingua;
                @Lingua.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnLingua;
                @ScattoAcqua.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnScattoAcqua;
                @ScattoAcqua.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnScattoAcqua;
                @ScattoAcqua.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnScattoAcqua;
                @Interazione.started -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnInterazione;
                @Interazione.performed -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnInterazione;
                @Interazione.canceled -= m_Wrapper.m_GiocatoreActionsCallbackInterface.OnInterazione;
            }
            m_Wrapper.m_GiocatoreActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movimento.started += instance.OnMovimento;
                @Movimento.performed += instance.OnMovimento;
                @Movimento.canceled += instance.OnMovimento;
                @RotazioneVista.started += instance.OnRotazioneVista;
                @RotazioneVista.performed += instance.OnRotazioneVista;
                @RotazioneVista.canceled += instance.OnRotazioneVista;
                @Salto.started += instance.OnSalto;
                @Salto.performed += instance.OnSalto;
                @Salto.canceled += instance.OnSalto;
                @MeleeAtk.started += instance.OnMeleeAtk;
                @MeleeAtk.performed += instance.OnMeleeAtk;
                @MeleeAtk.canceled += instance.OnMeleeAtk;
                @Lingua.started += instance.OnLingua;
                @Lingua.performed += instance.OnLingua;
                @Lingua.canceled += instance.OnLingua;
                @ScattoAcqua.started += instance.OnScattoAcqua;
                @ScattoAcqua.performed += instance.OnScattoAcqua;
                @ScattoAcqua.canceled += instance.OnScattoAcqua;
                @Interazione.started += instance.OnInterazione;
                @Interazione.performed += instance.OnInterazione;
                @Interazione.canceled += instance.OnInterazione;
            }
        }
    }
    public GiocatoreActions @Giocatore => new GiocatoreActions(this);

    // Generali
    private readonly InputActionMap m_Generali;
    private IGeneraliActions m_GeneraliActionsCallbackInterface;
    private readonly InputAction m_Generali_Pausa;
    public struct GeneraliActions
    {
        private @InputManager m_Wrapper;
        public GeneraliActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pausa => m_Wrapper.m_Generali_Pausa;
        public InputActionMap Get() { return m_Wrapper.m_Generali; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneraliActions set) { return set.Get(); }
        public void SetCallbacks(IGeneraliActions instance)
        {
            if (m_Wrapper.m_GeneraliActionsCallbackInterface != null)
            {
                @Pausa.started -= m_Wrapper.m_GeneraliActionsCallbackInterface.OnPausa;
                @Pausa.performed -= m_Wrapper.m_GeneraliActionsCallbackInterface.OnPausa;
                @Pausa.canceled -= m_Wrapper.m_GeneraliActionsCallbackInterface.OnPausa;
            }
            m_Wrapper.m_GeneraliActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pausa.started += instance.OnPausa;
                @Pausa.performed += instance.OnPausa;
                @Pausa.canceled += instance.OnPausa;
            }
        }
    }
    public GeneraliActions @Generali => new GeneraliActions(this);
    public interface IGiocatoreActions
    {
        void OnMovimento(InputAction.CallbackContext context);
        void OnRotazioneVista(InputAction.CallbackContext context);
        void OnSalto(InputAction.CallbackContext context);
        void OnMeleeAtk(InputAction.CallbackContext context);
        void OnLingua(InputAction.CallbackContext context);
        void OnScattoAcqua(InputAction.CallbackContext context);
        void OnInterazione(InputAction.CallbackContext context);
    }
    public interface IGeneraliActions
    {
        void OnPausa(InputAction.CallbackContext context);
    }
}
